### ISSUE TITLE
Can't access php file because of Domoticz

### ISSUE THREAD

**Issue by MathijsG** [dswinton/domo-ifttt#3]
Hi,

Because of Controlicz getting payware i'm trying one of the alternatives and I stumbled upon your solution. However I've getting a hard time reachting the php file, even locally at first. I get the Domoticz offline page instead of the PHP file when trying to reach it.

Did you try anything special to get it working?

I dropped the file in the www folder of the domoticz folder, where the index file of domoticz also resides. But it looks like Domoticz is preventing any manual access to a PHP file.

I'm running Raspbian on a Raspberry Pi.

**Comment by TheDukeSr** [comment]
Domoticz has no PHP support, install Apache or another webserver (advice: on the same device) and put this script there.

**Comment by TheDukeSr** [comment]
Domoticz has no PHP support, install Apache or another webserver (advice: on the same device) and put this script there.
PS. just updated my forked version with scenes and group support, might wanna have a look at that.
